# Generated by Django 4.1.1 on 2022-09-27 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='products-img/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products-img/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products-img/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('count', models.IntegerField()),
                ('type', models.CharField(choices=[('1', 'dona'), ('2', 'litr'), ('3', 'm2')], max_length=200)),
                ('currency', models.CharField(choices=[('1', "so'm"), ('2', 'dollar')], max_length=200)),
                ('entry_price', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('company', models.CharField(max_length=500)),
                ('barcode', models.CharField(default=0, max_length=100)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('seens', models.ManyToManyField(blank=True, related_name='seens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_shop', models.BooleanField(default=False)),
                ('lock_user', models.BooleanField(default=False)),
                ('cleated', models.DateTimeField(auto_now_add=True)),
                ('all_products_price', models.IntegerField()),
                ('money_type', models.CharField(choices=[('1', "so'm"), ('2', 'dollar')], max_length=200)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.chat')),
                ('products', models.ManyToManyField(related_name='Products', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop-images/%Y/')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(max_length=1000)),
                ('password', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('admins', models.ManyToManyField(blank=True, null=True, related_name='Admins', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='Members', to=settings.AUTH_USER_MODEL)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('product', models.ManyToManyField(to='home.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='chat_voices/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sended_by_shop', models.BooleanField(default=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.chat')),
                ('spiska', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.spiska')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.region'),
        ),
        migrations.AddField(
            model_name='chat',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shop'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
