# Generated by Django 4.1.4 on 2022-12-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eproduct_discount_eproduct_dollar_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_dollar',
            field=models.IntegerField(default=0),
        ),
    ]
