# Generated by Django 4.1.1 on 2022-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chat_id_alter_district_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percent',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
