# Generated by Django 4.1.4 on 2022-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_price_in_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_in_dollar',
            field=models.FloatField(default=0),
        ),
    ]
