# Generated by Django 4.1.1 on 2022-10-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_promocode_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='product',
            new_name='products',
        ),
    ]
