# Generated by Django 4.1.1 on 2022-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_promocode_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, to='home.product'),
        ),
    ]
