# Generated by Django 4.0.1 on 2022-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_promocode_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, to='home.Product'),
        ),
        migrations.AlterField(
            model_name='spiska',
            name='products',
            field=models.ManyToManyField(related_name='Products', to='home.Product'),
        ),
    ]
