# Generated by Django 4.1.3 on 2022-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_promocode_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
