# Generated by Django 4.1.3 on 2022-11-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_shop_currency_shop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='spiska',
        ),
        migrations.RenameField(
            model_name='spiska',
            old_name='cleated',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='spiska',
            name='chat',
        ),
        migrations.AddField(
            model_name='spiska',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spiska',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
