# Generated by Django 4.0.1 on 2022-12-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shop_currency_shop_type_alter_promocode_products_and_more'),
        ('home', '0007_remove_message_chat_remove_message_spiska_and_more'),
    ]

    operations = [
    ]
