# Generated by Django 4.0.1 on 2022-12-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20221207_1952'),
        ('home', '0008_merge_20221208_0127'),
    ]

    operations = [
    ]
