# Generated by Django 4.1.4 on 2022-12-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_price_alter_product_entry_price_category'),
        ('home', '0010_product_price_alter_product_entry_price_category'),
    ]

    operations = [
    ]
